In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('under5MortalityRate.csv', encoding='utf-8')
df

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Both sexes,60.27 [47.44-74.62]
1,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Male,63.83 [50.04-79.16]
2,Afghanistan,2019,Under-five mortality rate (probability of dyin...,Female,56.57 [44.54-70.18]
3,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Both sexes,62.54 [50.64-75.41]
4,Afghanistan,2018,Under-five mortality rate (probability of dyin...,Male,66.08 [53.41-79.76]
...,...,...,...,...,...
29994,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Both sexes,96.97 [87.36-107.7]
29995,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Male,102.6 [92.14-114]
29996,Timor-Leste,2002,Under-five mortality rate (probability of dyin...,Female,91.04 [81.92-101.5]
29997,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Both sexes,102.5 [92.72-113.3]
29998,Timor-Leste,2001,Under-five mortality rate (probability of dyin...,Male,108.2 [97.57-120]